(apply list '(1 2 3))
(apply list '(4 5 6 7 8 9 #(1 2 3) #t))
(apply list '(1 2 3))
(apply cons '(4 5))
(apply = '(4 4))
(apply list '())
(apply boolean? '(#t))
(apply char? '(#\a))
(apply integer? '(1))
(apply not '(#t))
(apply not '(#f))
(apply not '(5))
(apply null? '(1))
(apply null? '(()))
(apply pair? '((1 . 2)))
(apply rational? '(1/2))
(apply string? '("hi liad it's neta"))
(apply < '(5 3 4 6))
(apply < '(1))
(apply denominator '(1/2))
(apply numerator '(1/2))